# **<center>Killing A Neuron🔪🧠<center>**

In [141]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from copy import deepcopy
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix
keras.utils.set_random_seed(69)
data=pd.read_csv('Random_Exp_Data.csv')
data.drop('Unnamed: 0',axis=1,inplace=True)
data.head()

C_0       C_1       C_2       C_3  target
0 -1.172354 -0.533254 -1.284619  1.452159       0
1 -2.051463 -1.496670  1.824016 -1.881343       0
2 -2.908707 -1.720212  0.605944 -1.197363       2
3 -1.799285 -1.060268 -0.667529  1.139232       0
4 -1.673138 -0.553859 -0.621898 -1.239415       2

In [142]:
X=data.drop('target',axis=1)
y=data['target'].to_numpy()

In [143]:
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(y.reshape(-1,1))
y=enc.transform(y.reshape(-1,1)).toarray()

In [144]:
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.25, random_state=69)

In [145]:
model = Sequential()
model.add(Dense(3, input_dim = 4, activation = 'relu'))
model.add(Dense(3, activation = 'relu'))
model.add(Dense(3, activation = 'softmax'))

In [146]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.fit(x_train, y_train, epochs = 15, batch_size = 5)
scores = model.evaluate(x_test, y_test)
y_pred=model.predict(x_test)
y_pred_l=[]
for i in range(len(y_pred)):
    max_=np.argmax(y_pred[i])
    y_pred_l.append(max_)
y_pred_l=np.array(y_pred_l)
y_test_l=[]
for i in range(len(y_test)):
    max_=np.argmax(y_test[i])
    y_test_l.append(max_)
y_test_l=np.array(y_test_l)

Epoch 1/15


150/150 [==============================] - 1s 2ms/step - loss: 1.2571 - accuracy: 0.2267
Epoch 2/15
150/150 [==============================] - 0s 2ms/step - loss: 1.1602 - accuracy: 0.2373
Epoch 3/15
150/150 [==============================] - 0s 2ms/step - loss: 1.1149 - accuracy: 0.2853
Epoch 4/15
150/150 [==============================] - 0s 2ms/step - loss: 1.0807 - accuracy: 0.4347
Epoch 5/15
150/150 [==============================] - 0s 1ms/step - loss: 1.0440 - accuracy: 0.4920
Epoch 6/15
150/150 [==============================] - 0s 1ms/step - loss: 0.9923 - accuracy: 0.5093
Epoch 7/15
150/150 [==============================] - 0s 1ms/step - loss: 0.9262 - accuracy: 0.5360
Epoch 8/15
150/150 [==============================] - 0s 1ms/step - loss: 0.8568 - accuracy: 0.6347
Epoch 9/15
150/150 [==============================] - 0s 2ms/step - loss: 0.7870 - accuracy: 0.7093
Epoch 10/15
150/150 [==============================] - 0s 2ms/step - loss: 0.7284 - accuracy: 0.7507
Epoch 11/1

In [147]:
confusion_matrix(y_test_l,y_pred_l)

array([[72,  0,  5],
       [ 0, 65, 15],
       [ 9, 13, 71]], dtype=int64)

In [148]:
weights = np.array(model.get_weights(),dtype=object)

In [149]:
a = deepcopy(weights)

In [150]:
for i in range(3):
    for j in range(3):
        a = deepcopy(weights)
        print(f'Killing Neuron {j} in Layer {i}')
        neuron_weights = a[2*i][:,j]
        neuron_bias = a[2*i+1][j]
        neuron_weights[:]=0
        neuron_bias=0
        a[2*i][:,j]=neuron_weights
        a[2*i+1][j]=neuron_bias
        model.set_weights(a)
        scores = model.evaluate(x_test, y_test)
        y_pred=model.predict(x_test)
        y_pred_l=[]
        for k in range(len(y_pred)):
            max_=np.argmax(y_pred[k])
            y_pred_l.append(max_)
        y_pred_l=np.array(y_pred_l)
        y_test_l=[]
        for k in range(len(y_test)):
            max_=np.argmax(y_test[k])
            y_test_l.append(max_)
        y_test_l=np.array(y_test_l)
        print(confusion_matrix(y_test_l,y_pred_l))
    

Killing Neuron 0 in Layer 0
8/8 [==============================] - 0s 1ms/step
[[73  2  2]
 [ 5 74  1]
 [65 25  3]]
Killing Neuron 1 in Layer 0
8/8 [==============================] - 0s 2ms/step
[[73  0  4]
 [67  0 13]
 [22  0 71]]
Killing Neuron 2 in Layer 0
8/8 [==============================] - 0s 1ms/step
[[23  0 54]
 [ 0 65 15]
 [ 2 15 76]]
Killing Neuron 0 in Layer 1
8/8 [==============================] - 0s 1ms/step
[[72  0  5]
 [ 1  0 79]
 [10  0 83]]
Killing Neuron 1 in Layer 1
8/8 [==============================] - 0s 1ms/step
[[ 0 32 45]
 [ 0 65 15]
 [ 0 16 77]]
Killing Neuron 2 in Layer 1
8/8 [==============================] - 0s 1ms/step
[[73  0  4]
 [ 0 70 10]
 [14 19 60]]
Killing Neuron 0 in Layer 2
8/8 [==============================] - 0s 1ms/step
[[71  0  6]
 [ 1 65 14]
 [21 13 59]]
Killing Neuron 1 in Layer 2
8/8 [==============================] - 0s 2ms/step
[[71  1  5]
 [ 0 55 25]
 [ 9 26 58]]
Killing Neuron 2 in Layer 2
8/8 [==============================] - 0s 1m